//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO
    {
        public Nullable<int> PERMISO_ID { get; set; }
        public string FORMULARIO_ID { get; set; }
        public int ACCESO_ID { get; set; }
    }
}
