//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMO()
        {
            this.FACTURA_DETALLE_POS = new HashSet<FACTURA_DETALLE_POS>();
            this.ORDEN_COMPRA_DETALLE_POS = new HashSet<ORDEN_COMPRA_DETALLE_POS>();
            this.ORDEN_DE_PRODUCCION_DETALLE_POS = new HashSet<ORDEN_DE_PRODUCCION_DETALLE_POS>();
            this.SOLICITUD_PEDIDO_DETALLE_POS = new HashSet<SOLICITUD_PEDIDO_DETALLE_POS>();
            this.STOCK = new HashSet<STOCK>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
    
        public int INSUMO_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNIDAD_DE_MEDIDA { get; set; }
        public Nullable<int> CANTIDAD_MINIMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_DETALLE_POS> FACTURA_DETALLE_POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRA_DETALLE_POS> ORDEN_COMPRA_DETALLE_POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_DE_PRODUCCION_DETALLE_POS> ORDEN_DE_PRODUCCION_DETALLE_POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD_PEDIDO_DETALLE_POS> SOLICITUD_PEDIDO_DETALLE_POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK> STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
