//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DE_PRODUCCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_DE_PRODUCCION()
        {
            this.ORDEN_DE_PRODUCCION_DETALLE_POS = new HashSet<ORDEN_DE_PRODUCCION_DETALLE_POS>();
        }
    
        public int ORDEN_PROD_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TEXTO { get; set; }
        public Nullable<System.DateTime> FECHA_LIMITE { get; set; }
        public string ESTADO { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_DE_PRODUCCION_DETALLE_POS> ORDEN_DE_PRODUCCION_DETALLE_POS { get; set; }
    }
}
