//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DE_PRODUCCION_DETALLE_POS
    {
        public int ORDEN_PROD_DETALLE_POS { get; set; }
        public int ORDEN_PROD_ID { get; set; }
        public Nullable<int> POSICION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string TEXTO { get; set; }
        public int INSUMO_ID { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual ORDEN_DE_PRODUCCION ORDEN_DE_PRODUCCION { get; set; }
    }
}
