//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_PEDIDO_DETALLE_POS
    {
        public int SOLICITUD_PEDIDO_DETALLE_POST_ID { get; set; }
        public int SOLICITUD_PEDIDO_ID { get; set; }
        public string ESTADO { get; set; }
        public int INSUMO_ID { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string TEXTO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual SOLICITUD_PEDIDO SOLICITUD_PEDIDO { get; set; }
    }
}
