//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXTO
    {
        public int TEXTO_ID { get; set; }
        public int IDIOMA_ID { get; set; }
        public int FORMULARIO_ID { get; set; }
        public int COMPONEMTE_ID { get; set; }
        public string TEXTO1 { get; set; }
    }
}
