//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISCOMEntities : DbContext
    {
        public SISCOMEntities()
            : base("name=SISCOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESO> ACCESO { get; set; }
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<FACTURA_DETALLE_POS> FACTURA_DETALLE_POS { get; set; }
        public virtual DbSet<INSUMO> INSUMO { get; set; }
        public virtual DbSet<ORDEN_COMPRA_DETALLE_POS> ORDEN_COMPRA_DETALLE_POS { get; set; }
        public virtual DbSet<ORDEN_DE_COMPRA> ORDEN_DE_COMPRA { get; set; }
        public virtual DbSet<ORDEN_DE_PRODUCCION> ORDEN_DE_PRODUCCION { get; set; }
        public virtual DbSet<ORDEN_DE_PRODUCCION_DETALLE_POS> ORDEN_DE_PRODUCCION_DETALLE_POS { get; set; }
        public virtual DbSet<PERMISO> PERMISO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<REMITO> REMITO { get; set; }
        public virtual DbSet<REMITO_DETALLE_POS> REMITO_DETALLE_POS { get; set; }
        public virtual DbSet<SOLICITUD_PEDIDO> SOLICITUD_PEDIDO { get; set; }
        public virtual DbSet<SOLICITUD_PEDIDO_DETALLE_POS> SOLICITUD_PEDIDO_DETALLE_POS { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<TEXTO> TEXTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
